#!/bin/bash
# This script updates the locales for GOsa core and all plugins at once
ROOTDIR=`pwd`
COREDIR=$ROOTDIR/gosa-core
PLUGINDIR=$ROOTDIR/gosa-plugins
UPDATER=$ROOTDIR/gosa-core/update-locale

#execute updater in directory $1
update_locale() {
  WRKDIR=$1
  NAME=$2
  cd $WRKDIR
  echo "Updating $NAME in $WRKDIR"
  $UPDATER -y
  RC=$?
  if [[ $RC != 0 ]]; then
    echo "Updater failed"
    exit 1;
  fi
  if [ $ASSUME_Y -eq 0 ]; then
    echo "Press RETURN after you checked that the update went OK, press Ctrl-C to abort"
    read
  fi
  if [ $COMMIT -eq 1 ]; then
    echo "resetting commit cache"
    git reset
    RC=$?
    if [[ $RC != 0 ]]; then
      echo "git reset failed"
      exit 1;
    fi
    echo "adding locale/ dir"
    git add locale
    RC=$?
    if [[ $RC != 0 ]]; then
      echo "git add failed"
      exit 1;
    fi
    echo "committing"
    git commit -m "$NAME: locale update"
    RC=$?
    if [[ $RC != 0 ]]; then
      echo "git commit failed"
      exit 1;
    fi
    if [ $ASSUME_Y -eq 0 ]; then
      echo "Press RETURN after you checked that the commit went OK, press Ctrl-C to abort"
      read
    fi
  fi

}

#walk through plugin dir and call updater for each one, then update core
update_locales() {
  #first update plugins
  cd $PLUGINDIR
  for file in $PLUGINDIR/*; do
    if [ -d "$file" ]; then
      PLUGINDIR=`basename $file`
      PLUGINNAME=`echo plugins/$PLUGINDIR`
      update_locale $file $PLUGINNAME
    fi
  done
  
  #now update core
  PLUGINDIR=$COREDIR
  PLUGINNAME="core"
  update_locale $PLUGINDIR $PLUGINNAME
}

COMMIT=0
ASSUME_Y=0;
while getopts ":cyh" opt
do
  case $opt in
    c) COMMIT=1;
       ;;
    y)
       ASSUME_Y=1;
       ;;
    h|--help)
       echo "Usage: $(basename $0) [-c] [-y]"
       echo "       -c call git commit after each directory update"
       echo "       -y proceed without interruption"
       exit 1
       ;;
  esac
done

update_locales
